### PR TITLE
Added Xcode proj for existing classes and assets

### PR DESCRIPTION
**Pull request by ravi-paystack**
The framework folder is missing .xcodeproj, adding it to help with adding tests and organizing the project.

### CODE REVIEW

**Review by jubril-paystack — COMMENTED** [review]
@ravi-paystack Looks good! But shouldn't we exclude pods from the files being linted?

**Comment by ahmed-paystack** [comment]
Thanks, @ravi-paystack for this PR. I have 2 questions just to get some clarification please:

1. Saying that we're adding .xcodeproj to the framework, does that mean that we're adding a wrapper application around the framework to run it standalone?
2. I see there's a folder called Example with Alamofire code. Is that part of the SDK? If not, can we remove that?

**Comment by ravi-paystack** [comment]
> @ravi-paystack Looks good! But shouldn't we exclude pods from the files being linted?

@jubril-paystack  thanks for pointing out. I didn't exclude it thinking that the SDK doesn't use any pods but totally forgot about the example project having them. Thanks, it is fixed now 👍🏽

**Comment by ravi-paystack** [comment]
> Thanks, @ravi-paystack for this PR. I have 2 questions just to get some clarification please:
> 
> 1. Saying that we're adding .xcodeproj to the framework, does that mean that we're adding a wrapper application around the framework to run it standalone?
> 2. I see there's a folder called Example with Alamofire code. Is that part of the SDK? If not, can we remove that?

@ahmed-paystack to answer your questions,

1. The SDK currently doesn't have any Xcode project or workspace , it is currently accessed as a development pod via example project. Having a separate xcodeproject for it will allow us to configure and test the sdk seperately.
2. The example project is needed I guess. As far as I understand this is included to show users of our SDK how to include and use our SDK within an app. I don't think we can remove it. @jubril-paystack  can confirm on that.

**Comment by ahmed-paystack** [comment]
Hey @ravi-paystack, I believe we already had a conversation about this. I will look into the issues faced with unit tests using Fastlane. Can you please find a way to either re-create this PR with signed commits? Otherwise, this will be blocked for merging to master.

**Review by ahmed-paystack — APPROVED** [review]

**Review by jubril-paystack — APPROVED** [review]

**Comment by ravi-paystack** [comment]
Closing the PR since all commits are not signed

**Pull request closed without merging**
